// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7oVarxCgYwtrp__DHmZJa0nqqThBz-WM',
    appId: '1:534686622957:web:f54d93cb9336452bea98e4',
    messagingSenderId: '534686622957',
    projectId: 'skillspath-8ee30',
    authDomain: 'skillspath-8ee30.firebaseapp.com',
    storageBucket: 'skillspath-8ee30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvLSQd2FhCeOZXYX305w0SgRCXlD3Med4',
    appId: '1:534686622957:android:67d6d6a3227e1507ea98e4',
    messagingSenderId: '534686622957',
    projectId: 'skillspath-8ee30',
    storageBucket: 'skillspath-8ee30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWxjBMyyF77jUUqk14hE1bGRYDTMJ4PLA',
    appId: '1:534686622957:ios:1fb42c1cd1b0d870ea98e4',
    messagingSenderId: '534686622957',
    projectId: 'skillspath-8ee30',
    storageBucket: 'skillspath-8ee30.firebasestorage.app',
    iosBundleId: 'com.example.skillsPathApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWxjBMyyF77jUUqk14hE1bGRYDTMJ4PLA',
    appId: '1:534686622957:ios:1fb42c1cd1b0d870ea98e4',
    messagingSenderId: '534686622957',
    projectId: 'skillspath-8ee30',
    storageBucket: 'skillspath-8ee30.firebasestorage.app',
    iosBundleId: 'com.example.skillsPathApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7oVarxCgYwtrp__DHmZJa0nqqThBz-WM',
    appId: '1:534686622957:web:77db9fa817115e84ea98e4',
    messagingSenderId: '534686622957',
    projectId: 'skillspath-8ee30',
    authDomain: 'skillspath-8ee30.firebaseapp.com',
    storageBucket: 'skillspath-8ee30.firebasestorage.app',
  );
}
